# References:
# https://some-natalie.dev/blog/kaniko-in-arc/
# https://dev.to/ipo/using-kaniko-to-build-and-publish-container-image-with-github-action-on-github-self-hosted-runners-d5m

name: Image Build
on:
  push:
    tags:
    - "*"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  FEDORA_VERSION: 42
  DRIVER_VERSION: ${{ github.head_ref || github.ref_name }}
  # BASE_URL: https://us.download.nvidia.com/tesla

jobs:
  build:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: ghcr.io/randomcoww/kaniko:debug
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set tag
      run: |
        TARGETARCH=$(arch)
        echo BASE_URL=https://us.download.nvidia.com/XFree86/${TARGETARCH/x86_64/Linux-x86_64} | tee -a "$GITHUB_ENV"
        TARGETARCH=${TARGETARCH/x86_64/amd64} && TARGETARCH=${TARGETARCH/aarch64/arm64}

        JQ_VERSION=$(wget -O - https://api.github.com/repos/jqlang/jq/releases/latest | grep tag_name | cut -d '"' -f 4 | tr -d 'v')
        wget -O jq https://github.com/jqlang/jq/releases/download/$JQ_VERSION/jq-linux-$TARGETARCH
        chmod +x jq

        GOLANG_VERSION=$(wget -O - https://api.github.com/repos/golang/go/git/refs/tags | ./jq -r 'last(.[] | select(.ref | startswith("refs/tags/go")) | select(.ref | contains("rc") | not)).ref' | tr -d "refs/tags/go")
        echo GOLANG_VERSION=$GOLANG_VERSION | tee -a "$GITHUB_ENV"

        echo TAG=$(wget -O - https://gitlab.com/api/v4/projects/container-toolkit-fcos%2Fdriver/repository/tags | ./jq -r 'first(.[] | select(.name | endswith("-fedora"))).name') | tee -a "$GITHUB_ENV"
        echo TARGETARCH=$TARGETARCH | tee -a "$GITHUB_ENV"

    - name: Build and release container
      run: |
        mkdir -p $DOCKER_CONFIG
        cat > $DOCKER_CONFIG/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF

        /kaniko/executor \
          --context-sub-path="fedora" \
          --dockerfile="./Dockerfile" \
          --context="git://gitlab.com/container-toolkit-fcos/driver.git#$TAG" \
          --destination="ghcr.io/${{ github.repository }}:v$DRIVER_VERSION-fedora$FEDORA_VERSION" \
          --build-arg TARGETARCH=$TARGETARCH \
          --build-arg GOLANG_VERSION=$GOLANG_VERSION \
          --build-arg FEDORA_VERSION=$FEDORA_VERSION \
          --build-arg DRIVER_VERSION=$DRIVER_VERSION \
          --build-arg BASE_URL=$BASE_URL \
          --push-retry 3
  cleanup:
    needs:
      - build
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: docker.io/node:current-alpine
    permissions:
      packages: write
    steps:
      - name: Remove old container images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 4
          token: ${{ secrets.GITHUB_TOKEN }}